export const publicKey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCl1hcpOgxYS8NPvexOc46tV4K+
y+I9m/OFc+25wLgYbtvUr6l9DhtQRWBXqmLksfT32h8TcfPdAd48kuDP10H1FrUS
NuvvRseFCOwShxLPyUOacCXJQc5GxJ8KvaEhxtKVS0h5ZOCPu5CkcXqNxIU1YJXv
sNIJqhBllzVF6skoDQIDAQAB
-----END PUBLIC KEY-----`